### ISSUE TITLE
Failing assertion message is misleading (function timed out)

### ISSUE THREAD

**Issue by AlexandrosD** [timjroberts/cucumber-js-tsflow#4]
Hello,

I am setting up the test prototype for an Angular2 application, with protractor, protractor-cucumber-framework, **cucumber-tsflow**, and chai/chai-as-promised as the assertion framework.

In one of the step definitions, we have the folllowing code:

``` typescript
@then(/^something$/)
  private thenLoginIsSuccessful(callback: cucumber.CallbackStepDefinition): void {
    expect(alertPage.getTitle()).to.eventually.equal('Alert2').and.notify(callback);
    callback();
  };
```

The `alertPage.getTitle()` method gets the tilte (an `h1` element) of a page and returns `Promise<string>`. The actual titlte is **"Alert"**, so the previous assertion will fail.

Normally I would expect the error message to be something like "Expected "Alert" to be "Alert2", but instead the message that gets printed in the console is the following:
Now I see the following error in the results:

```
Failures:

1) Scenario: The user is fiddling with the alert showcase page - e2e\features\alert\alert.feature:12
   Step: Then title should be 'Alert2' - e2e\features\alert\alert.feature:7
   Step Definition: node_modules\cucumber-tsflow\dist\BindingDecorator.js:143
   Message:
     function timed out after 5000 milliseconds
```

This seems to be related to **promises** somehow, since If we update the assertion to something more straightforward, like `expect('Alert').to.equal('Alert2').and.notify(callback);`, the error I get is clear enough:

```
Failures:

1) Scenario: The user is showcasing a demo feature - e2e\features\demo.feature:3
   Step: Then it should display a the message 'app works!' - e2e\features\demo.feature:7
   Step Definition: node_modules\cucumber-tsflow\dist\BindingDecorator.js:140
   Message:
     AssertionError: expected 'Alert' to equal 'Alert2'
         at DemoSteps.thenAssertTitle (C:\tools\boilerplate-bdd\e2e\features\demo.steps.ts:31:28)
         at World.bindingFunc (C:\tools\boilerplate-bdd\node_modules\cucumber-tsflow\src\BindingDecorator.ts:145:85)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Note:** This issue was initially reported in the **chai-as-promised** project, https://github.com/domenic/chai-as-promised/issues/160

**Comment by AlexandrosD** [comment]
You may also check the sample project, https://github.com/AlexandrosD/ng2-protractor-cucumber
A simple `npm install` and `ng e2e` (angular-cli) will reproduce the reported error.

**Comment by timjroberts** [comment]
Thanks @AlexandrosD, I'll take a look as soon as I can.

**Comment by timjroberts** [comment]
At the moment, I'm unable to duplicate the issue @AlexandrosD. CucumberJS supports Promises directly so without any changes to cucumber-tsflow, the following works for me:

```javascript
@then(/^test$/)
public ThenTest(callback): void {
    chai.expect(Promise.resolve("Hello")).to.eventually.equal("Hello2").and.notify(callback);
}
```
and
```javascript
@then(/^test$/)
public ThenTest(callback): Promise<any> {
    return chai.expect(Promise.resolve("Hello")).to.eventually.equal("Hello2");
}
```

I'll take a look at your boilerplate project later on this evening, but if you try my second example (where I return the promise returned from chai-as-promised) then I think that will work. _I also think this is the better approach over notifying via the passed in callback_.

**Comment by AlexandrosD** [comment]
Hi @timjroberts and thank you for your efforts and help.

Unfortunately though, after performing the change you suggested we are getting the following error:
```
C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\runtime\stack_trace_filter.js:9
  var fileName = frame.getFileName() || '';
                      ^
TypeError: Cannot read property 'getFileName' of undefined
    at isFrameInCucumber (C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\runtime\stack_trace_filter.js:9:23)
    at Array.<anonymous> (C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\runtime\stack_trace_filter.js:15:9)
    at TraceModifier._modify (C:\tools\boilerplate-bdd\node_modules\stack-chain\stack-chain.js:44:32)
    at Function.prepareStackTrace (C:\tools\boilerplate-bdd\node_modules\stack-chain\stack-chain.js:119:25)
    at AssertionError.get stack (native)
    at handleStepResultEvent (C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\listener\json_formatter.js:102:59)
    at Object.run (C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\util\run.js:34:19)
    at Object.hear (C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\listener.js:15:23)
    at C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\runtime\event_broadcaster.js:28:18
    at iterate (C:\tools\boilerplate-bdd\node_modules\cucumber\lib\cucumber\util\async_for_each.js:7:7)
```

Another clarification that may heko you is that the `getTitle()` method returns a `webdriver.promise.Promise<text>` object.

Also, below are the version of each of of the involved packages (excerpt from `package.json`):
```
"chai": "^3.5.0",
"chai-as-promised": "^5.3.0",
"codelyzer": "0.0.20",
"cucumber": "^1.2.0",
"cucumber-tsflow": "^1.1.1"
```

**Comment by timjroberts** [comment]
@AlexandrosD - running `npm install` and then either `ng e2e` or `ng build` gives me the following error:
```bash
C:\ng2-protractor-cucumber [master ≡]> ng build
module.js:338
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\ng2-protractor-cucumber\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by AlexandrosD** [comment]
Sorry @timjroberts , it seems that you are missing the `angular-cli` npm package.

**Comment by timjroberts** [comment]
I've installed that globally?

**Comment by AlexandrosD** [comment]
Hm, I see, it seems that you're hitting this issue, https://github.com/angular/angular-cli/issues/1201, which appears to be solved with an update of npm. Mine is v3.9.5:
```
$ npm -v
3.9.5
```

**Comment by timjroberts** [comment]
That's fixed it @AlexandrosD.

So looking at your issue it appears to all work until the assertion fails. It's as CucumberJS isn't looking out for the promise to reject, and then just times out. It works with CucumberJS 1.0.0. I'm still investigating, so bear with me.

**Comment by AlexandrosD** [comment]
Thank you @timjroberts - If I could help somehow, let me know.

**Comment by timjroberts** [comment]
So I think the problem lies with CucumberJS 1.2.0, @AlexandrosD. It doesn't appear to treat promises the way it used to. Looking around some recent issues and the recent commits it would seem like they've introduced some core changes. I would guess that this is a bug. I'll put together an issue and open it over in that repo, but in the mean time, dropping back to CucumberJS 1.0.0 allows everything to work as expected.

**Comment by timjroberts** [comment]
Appears a few issues have crept into CucumberJS post 1.0.0:
https://github.com/cucumber/cucumber-js/issues/388#issuecomment-136729080

Will keep this issue open, but for the moment, I recommend using `cucumber@1.0.0`.

**Comment by AlexandrosD** [comment]
Thank you @timjroberts - very helpful!

I'll downgrade to `cucumber@1.0.0` as you suggest.

Thanks,
Alex

**Comment by AlexandrosD** [comment]
Confirmed - works like a charm with cucumber v1.0.0
